name: workmanager
description: Flutter Android Workmanager. This plugin allows you to schedule background work on Android with the Android WorkManager API. You will be given the chance to run some headless Dart code, handy for background synching mechanism. iOS is curently not supported since the API is vastly different.
version: 0.0.4
author: Tim Rijckaert <tim.rijckaert@gmail.com>
homepage: https://github.com/timrijckaert/flutter_workmanager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.tramckrijte.workmanager
    pluginClass: WorkmanagerPlugin
