name: workmanager
description: Flutter Android Workmanager
version: 0.0.1
author: Tim Rijckaert <tim.rijckaert@gmail.com>
homepage: https://github.com/timrijckaert/flutter_workmanager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.tramckrijte.workmanager
    pluginClass: WorkmanagerPlugin
